name: ImagePlugin
version: 1.0.0
main: net.akat.ImagePlugin
api-version: 1.21
author: 2FORWORD2
description: Плагин для создания картинок

commands:
  image:
    description: Управление изображениями и создание карт
    usage: /image <create|url|paint|list|reload|update|delete>
    aliases: [img]

permissions:
  imageplugin.*:
    description: Все права AkatImage
    default: op
    children:
      imageplugin.admin: true
      imageplugin.create: true
      imageplugin.create.url: true
      imageplugin.paint: true
      imageplugin.reload: true
      imageplugin.update: true
      imageplugin.delete: true
      imageplugin.list: true

  imageplugin.admin:
    description: Доступ ко всем командам ImagePlugin
    default: op

  imageplugin.create:
    description: Создание картинки из карт
    default: op

  imageplugin.create.url:
    description: Создание мозаики из URL
    default: op

  imageplugin.paint:
    description: Создание и сохранение картины в рамках
    default: op

  imageplugin.list:
    description: Просмотр списка картин
    default: op

  imageplugin.reload:
    description: Перезагрузка изображений
    default: op

  imageplugin.update:
    description: Повторная отрисовка всех картин
    default: op

  imageplugin.delete:
    description: Удаление сохраненной картины
    default: op
